export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const REMOVE_ALL_TRANSACTIONS = 'REMOVE_ALL_TRANSACTIONS';

export const SET_EXCHANGE_RATE = 'SET_EXCHANGE_RATE';

export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SORT_ASC = 'SORT_ASC';
export const SORT_DESC = 'SORT_DESC';
export const SORT_ALPHA = 'SORT_ALPHA';
